name:                BulletproofsPP
version:             0.1.0.0
github:              "liameagen/BulletproofsPP"
license:             BSD3
author:              "Liam Eagen"
maintainer:          "liameagen@protonmail.com"
copyright:           "2021 Liam Eagen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/liameagen/BulletproofsPP#readme>

dependencies:
    - QuickCheck
    - binary
    - SHA
    - cryptohash-sha256
    - base # >=4.7 && <5
    - bytestring
    - containers
    - deepseq
    - elliptic-curve
    - galois-field
    - groups
    - integer-gmp
    - mtl
    - protolude
    - random
    - semirings
    - tasty-quickcheck
    - vector-space
    - wl-pprint-text
    - ghc-typelits-natnormalise  
    - ghc-typelits-knownnat
    - parallel
    - vector
    - vector-th-unbox
    - aeson
    - text
    - optparse-applicative
    - cryptonite                # FFI EC operations for 25519

library:
  source-dirs: src
  ghc-options:
  - -O2
  default-extensions:
  - TypeFamilies
  - GeneralizedNewtypeDeriving
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - ConstraintKinds
  - TupleSections
  - BangPatterns
  - FlexibleContexts
  - DataKinds
  - ScopedTypeVariables
  - KindSignatures

executables:
  BulletproofsPP-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - BulletproofsPP

tests:
  BulletproofsPP-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BulletproofsPP
